name: iti_project
description: "A new Flutter project."
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  fluttertoast: ^8.2.12
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  intl: ^0.19.0
  flex_color_picker: ^3.5.1
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  cloud_firestore: ^6.0.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
