// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0L3dY5KE39-XjN5_pLXc3vBdq7twyv3A',
    appId: '1:607764376974:web:716590b50a3f09764a88df',
    messagingSenderId: '607764376974',
    projectId: 'final-project-bf031',
    authDomain: 'final-project-bf031.firebaseapp.com',
    storageBucket: 'final-project-bf031.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb6QIcRMR8t-npwofF1wXa3mR7p4_nLYk',
    appId: '1:607764376974:android:db779aa80ee1a6944a88df',
    messagingSenderId: '607764376974',
    projectId: 'final-project-bf031',
    storageBucket: 'final-project-bf031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE00LofuRYnZo7Luc3uS1tF_QZHWXEkn8',
    appId: '1:607764376974:ios:44966741493206964a88df',
    messagingSenderId: '607764376974',
    projectId: 'final-project-bf031',
    storageBucket: 'final-project-bf031.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE00LofuRYnZo7Luc3uS1tF_QZHWXEkn8',
    appId: '1:607764376974:ios:44966741493206964a88df',
    messagingSenderId: '607764376974',
    projectId: 'final-project-bf031',
    storageBucket: 'final-project-bf031.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0L3dY5KE39-XjN5_pLXc3vBdq7twyv3A',
    appId: '1:607764376974:web:7a047ba16da6032c4a88df',
    messagingSenderId: '607764376974',
    projectId: 'final-project-bf031',
    authDomain: 'final-project-bf031.firebaseapp.com',
    storageBucket: 'final-project-bf031.firebasestorage.app',
  );
}
